### PR TITLE
Made settings a bit more compressed

### PR DESCRIPTION
**Pull request by Aquafina-water-bottle**
This reduces unnecessary width within the settings dropdown. I figured that this will be an overall good change, so I didn't bother to add any option or width-specific options. However, as any UI change is somewhat opinionated, any and all feedback would be greatly appreciated. It might even be worth it to send the comparison pictures / prototype to some of the users to get feedback from them as well.

For general scalability, I believe the only problem will be when you want to add more icons to the top row. You might have to break it off into another row and/or wrap the text around the width of the icon.

Original:
image

Compressed:
image

P.S. I'm using the dark reader extension, so the colors may look a tiny bit off on the screenshots.

### CODE REVIEW

**Comment by Renji-XD** [comment]
Hello,

ty for the pr. 2 Suggestions:

- when going with the col span i think it looks better when the inputs are aligned with the checkbox labels below so i would remove the left margin on all of those elements
- no reason from my side to not immediately republish the page so maybe rebuild it already and add the docs folder change on top

**Comment by Aquafina-water-bottle** [comment]
@Renji-XD Just to clarify on the first suggestion, which version of the two below are you thinking of? I'm guessing the one on the right?
image

**Comment by Renji-XD** [comment]
@Aquafina-water-bottle ya right one though left is also fine.. as long as it is aligned with sth below ; )

**Comment by Aquafina-water-bottle** [comment]
I decided to do the one on the right as you said, and rebuilt the docs/index.html file. I'm not too sure why, but I didn't like the idea of having the text input fill the 3 column spaces all that much.

**Pull request merged**
